### ISSUE TITLE
Load Balance not working on Blizzard updates

### ISSUE THREAD

**Issue by RobertJamesMichael** [ti-mo/ansible-lanparty#20]
Hi Timo, since you added the "proxy_hide_header ETag" (in the blizzard depot configuration) I am testing the proxy again. The problem I have **is not because this new configuration**, I have tested with and without this line; I have four identical bandwidth ADSL connections (with load balancing configuration), when downloading without nginx there is no problem so the download is made trough all the connections, but when I use nginx only one connection is used at a time, its curious because the download is made through one connection for about 10-15 seconds and then it passes to other connection, the max speed reached is the speed of one connection. I haven't this issue before (last tested November 2016). Steam is performing better, it uses more than one connection at a time (but I thing this can perform better reaching the full capacity of the four connection, after many tests it reaches about 50% of the total connections capacity, but its 200% better that the blizzard updates).

Hope you have some ideas how to solve this. Thanks in advance !!!

**Comment by ti-mo** [comment]
Hi @fsalazar1977, thanks for reaching out. This is not within the scope of this project, but I'll leave the issue open since I've also observed this multiple times over while testing the Blizzard client. I have something you can try to improve this. Here is what I know:

- Blizzard Client supports persistent connections to the endpoint (cache/CDN), and this is widely used in production
- Blizzard Client only makes one request at a time to my endpoint (cache)
- Nginx supports persistent connections to the client while proxying, but _not_ for fetching from the CDN. This makes for a lot of overhead when fetching 1mb chunks like we do with slicing. The exception to this is `upstream your_upstream { keepalive 100; server 1.1.1.1:80; }` etc., but for that to fit our use case, it would require [this module](https://github.com/GUI/nginx-upstream-dynamic-servers) or any of its alternatives. (now I come to think of it, this wouldn't be such a bad idea) This would make our configuration incompatible with upstream Nginx.

I strongly suspect that the Blizzard client opens a connection to each of the addresses returned from a DNS query and tries to fetch from each endpoint in parallel. (this is why we ran into the ETag problem - chunks from the same file coming from different upstreams) In my case, this would be:

```
level3.blizzard.com.	86367	IN	CNAME	download.blizzard.com.c.footprint.net.
download.blizzard.com.c.footprint.net. 197 IN A	4.26.246.126
download.blizzard.com.c.footprint.net. 197 IN A	4.26.247.126

blzddist1-a.akamaihd.net. 300	IN	CNAME	blzddist1-a.akamaihd.net.edgesuite.net.
blzddist1-a.akamaihd.net.edgesuite.net.	21600 IN CNAME a1219.d.akamai.net.
a1219.d.akamai.net.	20	IN	A	173.223.106.33
a1219.d.akamai.net.	20	IN	A	173.223.106.42
```

Could you try to assign multiple addresses to your Nginx server and adding them to your DNS zone? Maybe this will cause the Blizzard client to open more parallel connections to your cache. (adding more records to /etc/hosts won't work - that lookup always returns on the first-found record)

**Comment by RobertJamesMichael** [comment]
Hi @ti-mo thanks for your help, it seems that is working this way, I will be doing more testing

**Comment by ti-mo** [comment]
@fasa1977 let me know if you have any further results, closing for now.
